[versions]
openrs2 = "0.1.0-SNAPSHOT"
bouncycastle = "1.70"

[libraries]
openrs2-deob-annotations = { module = "org.openrs2:openrs2-deob-annotations", version.ref = "openrs2" }
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
