name: Build and Release with Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Set Up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Replace ClientConfig.HOST_ADDRESS with PROD_IP
      run: sed -i "s/127.0.0.1/${{ secrets.PROD_IP }}/g" runescape/src/main/java/com/jagex/ClientConfig.java

    - name: Build the JAR
      run: ./gradlew jar --stacktrace

    - name: List JAR Location
      run: ls -R client/build/libs || echo "No files found in client/build/libs"

    - name: Rename and Archive JAR
      run: |
        mkdir -p release
        mv client/build/libs/client.jar client/build/libs/2011Scape-Client.jar || echo "client.jar not found"
        mv client/build/libs/2011Scape-Client.jar release/ || echo "Renamed JAR not found"
        echo "JAR moved to release/2011Scape-Client.jar"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          **Production Release**
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Build Timestamp: ${{ steps.time.outputs.formatted }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/2011Scape-Client.jar
        asset_name: 2011Scape-Client.jar
        asset_content_type: application/java-archive
