# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build with Gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - uses: gradle/actions/setup-gradle@v4

    - name: Replace ClientConfig.HOST_ADDRESS with PROD_IP
      run: sed -i "s/127.0.0.1/${{ secrets.PROD_IP }}/g" runescape/src/main/java/com/jagex/ClientConfig.java

    - run: ./gradlew build

    - name: Rename jar to 2011Scape-Client.jar
      run: mv client/build/libs/client.jar client/build/libs/2011Scape-Client.jar

    - uses: actions/upload-artifact@v4
      with:
        name: '2011Scape Client'
        path: client/build/libs/*
