name: Build with Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Build Production JAR
      run: ./gradlew -Penv=prod jar

    - name: Run Tests
      run: ./gradlew test

    - name: Archive Build Output
      run: mkdir -p release && mv build/libs/2011Scape-Client.jar release/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          **Production Release**
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Build Timestamp: ${{ steps.time.outputs.formatted }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/2011Scape-Client.jar
        asset_name: 2011Scape-Client.jar
        asset_content_type: application/java-archive

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build-artifacts
        path: build/
