name: Build and Release with Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11

    - name: Set Up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Replace ClientConfig.HOST_ADDRESS with PROD_IP
      run: sed -i "s/127.0.0.1/${{ secrets.PROD_IP }}/g" runescape/src/main/java/com/jagex/ClientConfig.java

    - name: Build the JAR
      run: ./gradlew jar --stacktrace

    - name: List JAR Files
      run: |
        echo "Listing files in client/build/libs:"
        ls -R client/build/libs || echo "No files found in client/build/libs"

    - name: Rename and Archive JAR
      run: |
        mkdir -p release
        mv client/build/libs/client.jar client/build/libs/2011Scape-Client.jar || echo "client.jar not found"
        mv client/build/libs/2011Scape-Client.jar release/ || echo "Renamed JAR not found"
        echo "JAR moved to release/2011Scape-Client.jar"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release v${{ github.run_number }}
        tag_name: v${{ github.run_number }}
        draft: false
        prerelease: false
        files: release/2011Scape-Client.jar
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
